create table items (
  id bigint generated by default as identity,
  item_name varchar(255),
  primary key (id)
);

create table book (
  id bigint not null,
  author varchar(255),
  isbn varchar(255),
  primary key (id)
);

create table movie (
  id bigint not null,
  duration integer not null,
  director varchar(255),
  primary key (id)
);

alter table if exists book add constraint book_id_fk foreign key (id) references items;
alter table if exists movie add constraint movie_id_fk foreign key (id) references items;